controller_manager:
  ros__parameters:
    update_rate: 50
    # These controllers must be loaded when the controller manager starts
    required_components: ['joint_state_broadcaster', 'diff_drive_controller']

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      name: joint_state_broadcaster

    # Diff Drive Controller
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      name: diff_drive_controller

      # Which joints does the diff drive control?
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]

      # Velocity commands come in on /cmd_vel (by default)
      use_stamped_vel: false
      publish_limited_velocity: true
      enable_odom_tf: true
      cmd_vel_timeout: 0.5
      linear.x.has_velocity_limits: true
      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      angular.z.has_velocity_limits: true
      angular.z.max_velocity: 2.0
      angular.z.min_velocity: -2.0
