# slam_toolbox_params.yaml
slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: "mapping"           # Options: "mapping" or "localization"
    base_frame: "base_link"
    odom_frame: "odom"
    scan_topic: "scan"
    map_update_interval: 5.0
    resolution: 0.05
